// Code generated by "stringer -type=ExtrapolationType"; DO NOT EDIT.

package bsplines

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExtrapolateZero-0]
	_ = x[ExtrapolateConstant-1]
	_ = x[ExtrapolateLinear-2]
}

const _ExtrapolationType_name = "ExtrapolateZeroExtrapolateConstantExtrapolateLinear"

var _ExtrapolationType_index = [...]uint8{0, 15, 34, 51}

func (i ExtrapolationType) String() string {
	if i < 0 || i >= ExtrapolationType(len(_ExtrapolationType_index)-1) {
		return "ExtrapolationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExtrapolationType_name[_ExtrapolationType_index[i]:_ExtrapolationType_index[i+1]]
}
